### ISSUE TITLE
Update SDK to be compliant with spec v0.2.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/dotnet-sdk#36]
Update the SDK to be compliant with the v0.2.0 spec.

## Flag Evaluation API
- [x]  [#116](https://github.com/open-feature/spec/pull/116) - Have different methods for float and int - https://github.com/open-feature/dotnet-sdk/pull/31

## Providers
- [x]  [#119](https://github.com/open-feature/spec/pull/119) - Remove context transformers. Add provider hooks - https://github.com/open-feature/dotnet-sdk/pull/38

## Evaluation Context
- [x]  [#117](https://github.com/open-feature/spec/pull/117) - Ensure context merging behavior is correct - https://github.com/open-feature/dotnet-sdk/pull/32
- [x]  [#120](https://github.com/open-feature/spec/pull/120) - Add the ability to fetch all custom fields -  https://github.com/open-feature/dotnet-sdk/pull/37
- [x]  [#121](https://github.com/open-feature/spec/pull/121) - Ensure evaluation context keys are unique - https://github.com/open-feature/dotnet-sdk/pull/32

## Hooks
- [x]  [#119](https://github.com/open-feature/spec/pull/119) - Ensure provider hook are correctly ordered - https://github.com/open-feature/dotnet-sdk/pull/38

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.1.0...v0.2.0

**Comment by benjiro** [comment]
Resolved Issues
https://github.com/open-feature/spec/pull/116 -> https://github.com/open-feature/dotnet-sdk/pull/31

**Comment by toddbaert** [comment]
I _think_ we'll be done when @benjiro 's [PR](https://github.com/open-feature/dotnet-sdk/pull/38) is merged, and when I complete this: https://github.com/open-feature/dotnet-sdk/pull/38#discussion_r941479156

**Comment by benjiro** [comment]
Version 0.1.2 has been release which is Spec v0.2.0 compliant
