### ISSUE TITLE
Update SDK to be compliant with spec v0.5.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/dotnet-sdk#71]
Update the SDK to be compliant with the v0.5.0 spec.

### ⚠ BREAKING CHANGES

- [x] https://github.com/open-feature/spec/pull/142 Error codes must be a constrained set of values (e.g. enum). #72

### Additional changes

- [x] https://github.com/open-feature/spec/pull/140 Clarify that `reason` must be a string in the `flag resolution details` and `evaluation details`.
- [x] https://github.com/open-feature/spec/pull/142 Add optional `error message` to `flag resolution details`. #72
 
## General

 - [x] Add/update a spec version badge on the readme. #74 

[![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.5.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.5.0)

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.4.0...v0.5.0

**Comment by kinyoklion** [comment]
Anyone mind if I pick this up?

**Comment by benjiro** [comment]
Closing as all specification 0.5.0 are now resolved
